### ISSUE TITLE
催更:sparkles:

### ISSUE THREAD

**Issue by Nagisazz** [TNumFive/log2what#1]
催更:sparkles:

**Comment by TNumFive** [comment]
基本目的已经实现了；
之前做就是想要弄个log工具，能够方便进行日志查找，譬如从文件名就能知道日志的开始日期而不是那种数字后缀，或者可以用数据库查找这种的；
不过目前的数据库插入实现太慢了，不知道是不是因为不是用批量插入的方式导致的

**Comment by TNumFive** [comment]
> 催更✨

基本目的已经实现了；
之前做就是想要弄个log工具，能够方便进行日志查找，譬如从文件名就能知道日志的开始日期而不是那种数字后缀，或者可以用数据库查找这种的；
不过目前的数据库插入实现太慢了，不知道是不是因为不是用批量插入的方式导致的

**Comment by TNumFive** [comment]
@Nagisazz 
是不是需要@才能看到消息？
基本目标达到了，，，感觉数据库拿来直接记log确实不合适。。。
